/**
 * Priority question config — maps question codes to priority metadata.
 *
 * Used by the signal-driven engine. Can be extended via DB metadata (merged at runtime).
 */

import type { OrganizationType } from '@/types/salesDiagnostic';
import type {
  QuestionPriorityModel,
  PainSignal,
  MaturitySignal,
  UrgencySignal,
  ProfileGapField,
} from './priorityEngine.types';

/** Tags that are BLOCKED for productor (Section 5) */
export const PRODUCTOR_BLOCKED_TAGS = [
  'cooperative_structure',
  'supplier_network',
  'how_many_producers_deliver',
] as const;

/** Question code → priority model. Extend as questions are added. */
export const PRIORITY_CONFIG: Record<string, Omit<QuestionPriorityModel, 'id'>> = {
  // Context
  CTX_ORG_TYPE: {
    code: 'CTX_ORG_TYPE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['context'],
    weight: 100,
    dependencies: [],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['organization_type'],
  },
  CTX_PRODUCERS: {
    code: 'CTX_PRODUCERS',
    applies_to: ['cooperativa', 'exportador', 'beneficio'],
    tags: ['cooperative_structure', 'supplier_network', 'how_many_producers_deliver'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['scale'],
  },
  // Pain
  PAIN_REJECT: {
    code: 'PAIN_REJECT',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['pain'],
    weight: 30,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['rejections'],
    gap_targets: ['pain_severity'],
  },
  PAIN_HOURS: {
    code: 'PAIN_HOURS',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['pain'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['manual_hours'],
    gap_targets: ['pain_severity'],
  },
  PAIN_VISIBILITY: {
    code: 'PAIN_VISIBILITY',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['pain'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['visibility_gap'],
    gap_targets: ['pain_severity'],
  },
  PAIN_COST: {
    code: 'PAIN_COST',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['pain'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['cost_impact'],
    gap_targets: ['pain_severity'],
  },
  PAIN_SEVERITY: {
    code: 'PAIN_SEVERITY',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['pain'],
    weight: 30,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['severity_high'],
    gap_targets: ['pain_severity'],
  },
  // Maturity
  MAT_SYSTEMS: {
    code: 'MAT_SYSTEMS',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['maturity'],
    weight: 22,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['legacy_systems'],
    gap_targets: ['maturity_level'],
  },
  MAT_MOBILE: {
    code: 'MAT_MOBILE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['maturity'],
    weight: 20,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['mobile_adoption'],
    gap_targets: ['maturity_level'],
  },
  MAT_CONNECTIVITY: {
    code: 'MAT_CONNECTIVITY',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['maturity'],
    weight: 20,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['connectivity'],
    gap_targets: ['maturity_level'],
  },
  MAT_DATA: {
    code: 'MAT_DATA',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['maturity'],
    weight: 18,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['data_format'],
    gap_targets: ['maturity_level'],
  },
  // Compliance
  COMP_EUDR_AWARE: {
    code: 'COMP_EUDR_AWARE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['compliance'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['certification_status'],
  },
  COMP_DUE_DILIGENCE: {
    code: 'COMP_DUE_DILIGENCE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['compliance'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['certification_status'],
  },
  COMP_GEO: {
    code: 'COMP_GEO',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['compliance'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['certification_status'],
  },
  COMP_AUDIT_READY: {
    code: 'COMP_AUDIT_READY',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['compliance'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['certification_status'],
  },
  // Urgency
  URG_TIMELINE: {
    code: 'URG_TIMELINE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['urgency'],
    weight: 30,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['timeline_short'],
    gap_targets: ['urgency_timeline'],
  },
  URG_HARVEST: {
    code: 'URG_HARVEST',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['urgency'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: ['harvest_soon'],
    gap_targets: ['urgency_timeline'],
  },
  // Fit
  FIT_NEED_TRACE: {
    code: 'FIT_NEED_TRACE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['fit'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: [],
  },
  FIT_OFFLINE: {
    code: 'FIT_OFFLINE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['fit'],
    weight: 22,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: [],
  },
  // Budget
  BUD_AVAILABLE: {
    code: 'BUD_AVAILABLE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['budget'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['budget_readiness'],
  },
  BUD_DECISION: {
    code: 'BUD_DECISION',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['budget'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['budget_readiness'],
  },
  BUD_RANGE: {
    code: 'BUD_RANGE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['budget'],
    weight: 30,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['budget_readiness'],
  },
  BUD_ROI: {
    code: 'BUD_ROI',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['budget'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['budget_readiness'],
  },
  BUD_TIMELINE: {
    code: 'BUD_TIMELINE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['budget'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['budget_readiness'],
  },
  BUD_CURRENT_SPEND: {
    code: 'BUD_CURRENT_SPEND',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['budget'],
    weight: 22,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['budget_readiness'],
  },
  // Objections
  OBJ_MAIN_CONCERN: {
    code: 'OBJ_MAIN_CONCERN',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['objections'],
    weight: 30,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['objection_profile'],
  },
  OBJ_PREV_FAIL: {
    code: 'OBJ_PREV_FAIL',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['objections'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['objection_profile'],
  },
  OBJ_COMPETITION: {
    code: 'OBJ_COMPETITION',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['objections'],
    weight: 20,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['objection_profile'],
  },
  OBJ_RESISTANCE: {
    code: 'OBJ_RESISTANCE',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['objections'],
    weight: 25,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['objection_profile'],
  },
  OBJ_TRUST: {
    code: 'OBJ_TRUST',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['objections'],
    weight: 28,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['objection_profile'],
  },
  OBJ_NEEDS: {
    code: 'OBJ_NEEDS',
    applies_to: ['productor', 'cooperativa', 'exportador', 'beneficio'],
    tags: ['objections'],
    weight: 30,
    dependencies: ['CTX_ORG_TYPE'],
    unlocks: [],
    signal_targets: [],
    gap_targets: ['objection_profile'],
  },
};

/** Answer value → profile field mapping (question_code → option_value → profile_value) */
export const ANSWER_TO_PROFILE: Record<
  string,
  Record<string, { field: keyof import('./priorityEngine.types').PriorityProfile; value: string }>
> = {
  CTX_ORG_TYPE: {
    cooperativa: { field: 'organization_type', value: 'cooperativa' },
    exportador: { field: 'organization_type', value: 'exportador' },
    productor: { field: 'organization_type', value: 'productor' },
    beneficio: { field: 'organization_type', value: 'beneficio' },
  },
  CTX_PRODUCERS: {
    '50_200': { field: 'scale', value: '50_200' },
    '200_500': { field: 'scale', value: '200_500' },
    '500_plus': { field: 'scale', value: '500_plus' },
  },
  PAIN_SEVERITY: {
    critical: { field: 'pain_severity', value: 'critical' },
    high: { field: 'pain_severity', value: 'high' },
    medium: { field: 'pain_severity', value: 'medium' },
    low: { field: 'pain_severity', value: 'low' },
  },
  URG_TIMELINE: {
    lt3m: { field: 'urgency_timeline', value: 'lt3m' },
    '3_6m': { field: 'urgency_timeline', value: '3_6m' },
    '6m_plus': { field: 'urgency_timeline', value: '6m_plus' },
  },
  BUD_AVAILABLE: {
    approved: { field: 'budget_readiness', value: 'approved' },
    pending: { field: 'budget_readiness', value: 'pending' },
    none: { field: 'budget_readiness', value: 'none' },
  },
};
